### ISSUE TITLE
Tab Completation is not blocked for players

### ISSUE THREAD

**Issue by CloudeLecaw** [dvargas135/eZProtector#5]
tab-completion:
  # disabled = blocked; if it's true, the tab completion will be blocked. (dumb explanation)
  disable: true

Player still can use the tabcompletation :3

**Comment by dvargas135** [comment]
Hello,

What version are you using which is not blocking the tab completion?

Thanks.

**Comment by Twi5TeD** [comment]
latest version im also getting this but i get kicked and an error in my bungee log

**Comment by dvargas135** [comment]
Fixed.

**Comment by Twi5TeD** [comment]
nope i have latest version still get kicked https://gyazo.com/45b3b8c43d20745068912086690d2e41

http://pastebin.com/MBmj92cK

**Comment by dvargas135** [comment]
@Twi5TeD this is not your issue. I'll check out yours, I honestly don't know what's causing it as I don't develop BungeeCord but I'll see what's wrong.
